### PR TITLE
implemented unity unit testing framework

### PR DESCRIPTION
**Pull request by Naitsabot**
Følte ikke lige at prøve at fetche det indirekte, så træk det bare direkte ind i test folder.
Clang-tidy ville nok ikke kunne lide det lol

### CODE REVIEW

**Comment by krestenlaust** [comment]
I'll look into it someday sunday or monday 👌

**Comment by krestenlaust** [comment]
Finally! that took way too long to figure out

**Review by krestenlaust — APPROVED** [review]
Nice

**Review by pSlessing — APPROVED** [review]
uhh, sure, lgtm

**Pull request merged**
